### PR TITLE
add support for loongarch64

### PR DESCRIPTION
**Pull request by yzewei**

### CODE REVIEW

**Comment by yzewei** [comment]
@tonistiigi Thanks!

**Review by crazy-max — CHANGES_REQUESTED** [review]
Thanks, please see https://github.com/tonistiigi/binfmt/pull/147/checks?check_run_id=18425341817 about missing DCO

**Comment by crazy-max** [comment]
See also the linting issue: https://github.com/tonistiigi/binfmt/actions/runs/6778986369/job/19055041125?pr=147#step:5:107

```
#13 [stage-0 5/5] RUN --mount=target=. --mount=target=/root/.cache,type=cache   golangci-lint run
#13 9.553 cmd/binfmt/config.go:69: File is not `gofmt`-ed with `-s` (gofmt)
#13 9.553                 binary: "qemu-loongarch64",
#13 9.553                 magic:  `\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x02\x01`,
#13 9.553                 mask:   `\xff\xff\xff\xff\xff\xff\xff\xfc\x00\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff`,
#13 9.553         },
#13 ERROR: process "/bin/sh -c golangci-lint run" did not complete successfully: exit code: 1
```

**Comment by yzewei** [comment]
I'm sorry to reply to you for such a long time. I have been busy recently. Now I have signed and modified the format error!

**Pull request closed without merging**
