### PR TITLE
Fix i386 arch

### PR DESCRIPTION
**Pull request by crazy-max**
cc @tonistiigi

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Review by tonistiigi — CHANGES_REQUESTED** [review]
Test failure. Iiuc it is just checking a bad case that doesn't pass on amd64 because 386 is natively supported there. Not via emulator.

**Comment by crazy-max** [comment]
@tonistiigi 

>  just checking a bad case that doesn't pass on amd64 because 386 is natively supported there. Not via emulator.

Yes I just saw that

**Review by tonistiigi — APPROVED** [review]

**Comment by tonistiigi** [comment]
@wanghuaiqing2010 mips has the same issue. Go arch is `mips64le`, not `mips64el`

**Comment by wanghuaiqing2010** [comment]
@tonistiigi I am trying to fix it.

**Comment by wanghuaiqing2010** [comment]
@tonistiigi I have already fixed it, please see the following link.
https://github.com/tonistiigi/binfmt/pull/26

**Pull request merged**
